spring:
  profiles:
      active: dev
  jpa:
    database: MYSQL


server:
  port: 8080


mybatis:
  typeAliasesPackage: com.talentservice.talentservice.entity
  mapperLocations: classpath:mapper/*.xml

---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/talent_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  session:
    store-type: none
